"""initial schema

Revision ID: ab54a48b74f6
Revises: 
Create Date: 2026-08-22 04:38:37.062397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab54a48b74f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('training_dataset', sa.String(length=100), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('calibration_score', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('cross_validation', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('model_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_is_production'), ['is_production'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_trained_at'), ['trained_at'], unique=False)

    op.create_table('raw_injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('team_name', sa.String(length=100), nullable=True),
    sa.Column('sport', sa.String(length=20), nullable=True),
    sa.Column('injury_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_injuries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_injuries_player_name'), ['player_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_injuries_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_injuries_reported_at'), ['reported_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_injuries_sport'), ['sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_injuries_team_name'), ['team_name'], unique=False)

    op.create_table('raw_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_game_id', sa.String(length=100), nullable=True),
    sa.Column('sport', sa.String(length=20), nullable=True),
    sa.Column('home_team', sa.String(length=100), nullable=True),
    sa.Column('away_team', sa.String(length=100), nullable=True),
    sa.Column('market_type', sa.String(length=20), nullable=True),
    sa.Column('outcome_name', sa.String(length=50), nullable=True),
    sa.Column('odds_american', sa.Integer(), nullable=True),
    sa.Column('odds_decimal', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_odds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_odds_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_odds_provider_game_id'), ['provider_game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_odds_sport'), ['sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_odds_timestamp'), ['timestamp'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('odds_american', sa.Integer(), nullable=True),
    sa.Column('win_probability', sa.Float(), nullable=True),
    sa.Column('bankroll', sa.Float(), nullable=True),
    sa.Column('bet_size', sa.Float(), nullable=True),
    sa.Column('bet_size_type', sa.String(length=20), nullable=True),
    sa.Column('num_bets', sa.Integer(), nullable=True),
    sa.Column('num_simulations', sa.Integer(), nullable=True),
    sa.Column('strategy_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_name'), ['name'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('league', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_league'), ['league'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_sport'), ['sport'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('league', sa.String(length=50), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('game_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_game_time'), ['game_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_sport'), ['sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_status'), ['status'], unique=False)

    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.String(length=20), nullable=True),
    sa.Column('injury_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injuries_player_name'), ['player_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_injuries_reported_at'), ['reported_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_injuries_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_injuries_sport'), ['sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_injuries_team_id'), ['team_id'], unique=False)

    op.create_table('model_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('avg_roi', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_evaluations_evaluated_at'), ['evaluated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_evaluations_model_id'), ['model_id'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_risk', sa.Float(), nullable=True),
    sa.Column('expected_roi', sa.Float(), nullable=True),
    sa.Column('kelly_exposure', sa.Float(), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_model_id'), ['model_id'], unique=False)

    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('odds_american', sa.Integer(), nullable=True),
    sa.Column('win_probability', sa.Float(), nullable=True),
    sa.Column('bankroll', sa.Float(), nullable=True),
    sa.Column('bet_size', sa.Float(), nullable=True),
    sa.Column('bet_size_type', sa.String(length=20), nullable=True),
    sa.Column('num_bets', sa.Integer(), nullable=True),
    sa.Column('num_simulations', sa.Integer(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_runs_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('game_id', sa.String(length=100), nullable=False),
    sa.Column('predicted_probability', sa.Float(), nullable=True),
    sa.Column('actual_outcome', sa.Boolean(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_results_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_results_model_id'), ['model_id'], unique=False)

    op.create_table('game_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=100), nullable=False),
    sa.Column('sportsbook', sa.String(length=50), nullable=True),
    sa.Column('market_type', sa.String(length=20), nullable=True),
    sa.Column('outcome_name', sa.String(length=50), nullable=True),
    sa.Column('odds_american', sa.Integer(), nullable=True),
    sa.Column('odds_decimal', sa.Float(), nullable=True),
    sa.Column('implied_probability', sa.Float(), nullable=True),
    sa.Column('is_no_vig', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_odds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_odds_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_odds_market_type'), ['market_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_odds_sportsbook'), ['sportsbook'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_odds_timestamp'), ['timestamp'], unique=False)

    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('game_id', sa.String(length=100), nullable=False),
    sa.Column('predicted_probability', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('fair_odds_decimal', sa.Float(), nullable=True),
    sa.Column('ev', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_model_id'), ['model_id'], unique=False)

    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=100), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('bet_type', sa.String(length=20), nullable=True),
    sa.Column('stake', sa.Float(), nullable=True),
    sa.Column('predicted_probability', sa.Float(), nullable=True),
    sa.Column('ev', sa.Float(), nullable=True),
    sa.Column('recommendation_stars', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_items_confidence_level'), ['confidence_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_items_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_items_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_run_id', sa.Integer(), nullable=False),
    sa.Column('run_index', sa.Integer(), nullable=True),
    sa.Column('final_bankroll', sa.Float(), nullable=True),
    sa.Column('is_profitable', sa.Boolean(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_results_final_bankroll'), ['final_bankroll'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_results_run_index'), ['run_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_results_simulation_run_id'), ['simulation_run_id'], unique=False)

    op.create_table('system_play_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_run_id', sa.Integer(), nullable=True),
    sa.Column('stated_probability', sa.Float(), nullable=True),
    sa.Column('actual_win_rate', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('calibration_status', sa.String(length=50), nullable=True),
    sa.Column('confidence_interval_low', sa.Float(), nullable=True),
    sa.Column('confidence_interval_high', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_play_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_play_results_calibration_status'), ['calibration_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_play_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_play_results_simulation_run_id'), ['simulation_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_play_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_play_results_simulation_run_id'))
        batch_op.drop_index(batch_op.f('ix_system_play_results_created_at'))
        batch_op.drop_index(batch_op.f('ix_system_play_results_calibration_status'))

    op.drop_table('system_play_results')
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_results_simulation_run_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_results_run_index'))
        batch_op.drop_index(batch_op.f('ix_simulation_results_final_bankroll'))

    op.drop_table('simulation_results')
    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_items_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_items_game_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_items_confidence_level'))

    op.drop_table('portfolio_items')
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_predictions_model_id'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_game_id'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_created_at'))

    op.drop_table('model_predictions')
    with op.batch_alter_table('game_odds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_odds_timestamp'))
        batch_op.drop_index(batch_op.f('ix_game_odds_sportsbook'))
        batch_op.drop_index(batch_op.f('ix_game_odds_market_type'))
        batch_op.drop_index(batch_op.f('ix_game_odds_game_id'))

    op.drop_table('game_odds')
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_results_model_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_results_game_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_results_created_at'))

    op.drop_table('backtest_results')
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_runs_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_runs_created_at'))

    op.drop_table('simulation_runs')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_model_id'))
        batch_op.drop_index(batch_op.f('ix_portfolios_date'))

    op.drop_table('portfolios')
    with op.batch_alter_table('model_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_evaluations_model_id'))
        batch_op.drop_index(batch_op.f('ix_model_evaluations_evaluated_at'))

    op.drop_table('model_evaluations')
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injuries_team_id'))
        batch_op.drop_index(batch_op.f('ix_injuries_sport'))
        batch_op.drop_index(batch_op.f('ix_injuries_severity'))
        batch_op.drop_index(batch_op.f('ix_injuries_reported_at'))
        batch_op.drop_index(batch_op.f('ix_injuries_player_name'))

    op.drop_table('injuries')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_status'))
        batch_op.drop_index(batch_op.f('ix_games_sport'))
        batch_op.drop_index(batch_op.f('ix_games_season'))
        batch_op.drop_index(batch_op.f('ix_games_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_games_game_time'))
        batch_op.drop_index(batch_op.f('ix_games_away_team_id'))

    op.drop_table('games')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_sport'))
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_league'))

    op.drop_table('teams')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_name'))

    op.drop_table('strategies')
    with op.batch_alter_table('raw_odds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_odds_timestamp'))
        batch_op.drop_index(batch_op.f('ix_raw_odds_sport'))
        batch_op.drop_index(batch_op.f('ix_raw_odds_provider_game_id'))
        batch_op.drop_index(batch_op.f('ix_raw_odds_provider'))

    op.drop_table('raw_odds')
    with op.batch_alter_table('raw_injuries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_injuries_team_name'))
        batch_op.drop_index(batch_op.f('ix_raw_injuries_sport'))
        batch_op.drop_index(batch_op.f('ix_raw_injuries_reported_at'))
        batch_op.drop_index(batch_op.f('ix_raw_injuries_provider'))
        batch_op.drop_index(batch_op.f('ix_raw_injuries_player_name'))

    op.drop_table('raw_injuries')
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_trained_at'))
        batch_op.drop_index(batch_op.f('ix_ml_models_name'))
        batch_op.drop_index(batch_op.f('ix_ml_models_is_production'))

    op.drop_table('ml_models')
    # ### end Alembic commands ###
